import { Inter } from "next/font/google"
import "./globals.css"
import Link from "next/link"
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"

const inter = Inter({ subsets: ["latin"] })

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <nav style={{width: '100%',
         background: 'teal',
          fontSize: '20px',
           height: '80px',
           display: 'flex',
           justifyContent: 'center',
           alignItems: 'center'
           }}>
          <Link style={{margin: '8px'}}  href="/">Home </Link>
          <Link style={{margin: '8px'}}  href="/actors">Actors </Link>
          <Link style={{margin: '8px'}} href="/genre">Genre </Link>
          <Link className=" bg-red-500" href="/movies">Movies </Link>
           
        </nav> */}
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  )
}
